// Registration/Frontend/UserBadge.vue
<template>
    <figure class="avatar avatar-md" :data-initial="initials" style="background-color: #5755d9;"></figure>
</template>

<script setup lang="ts">
import {onMounted, ref} from "vue";
import {fetchGet} from "../../Frontend/request";
import {getUserInfo} from "../../Frontend/auth";

const initials = ref("");

onMounted(async () => {
    const userInfo = getUserInfo();
    const result = await fetchGet<string>(`registration/initials/${userInfo.getValue().username}`);
    initials.value = result.getValue();
});
</script>

<style scoped>
figure {
    cursor: pointer;
}
</style>

// Registration/Frontend/userBadge.component.ts
﻿import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { AuthService } from "../../main-frontend-app/auth.service";
import { ResultOk } from "../../Starter/CommonTypes";

@Component({
    selector: "user-badge",
    template: `
        <figure class="avatar avatar-md" [attr.data-initial]="initials | async" style="background-color: #5755d9;"></figure>
    `,
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class UserBadgeComponent {
    public initials: Promise<string> | undefined;

    constructor(
        authService: AuthService
    ) {
        const info = authService.getUserInfo();
        if (info instanceof ResultOk) {
            this.initials = authService.get<string>(`/registration/initials/${info.value.UserName}`);
        }
    }
}

type Wallet = {
    walletId: string
}
